# Generated by Django 5.0.2 on 2024-02-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='phone',
            field=models.CharField(default=9094759020, max_length=255),
            preserve_default=False,
        ),
    ]
